#apiVersion: certmanager.k8s.io/v1alpha1
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bouc-io-tls-secret
  namespace: istio-system
spec:
  secretName: bouc-io-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: "${CLUSTER_DOMAIN}"
  # acme:
  #   config:
  #     - http01:
  #         ingress: istio
  #       domains:
  #         - npr.app.${CLUSTER_DOMAIN}
  dnsNames:
    - "kubernetes-dashboard.${CLUSTER_DOMAIN}"
    - "admin.${CLUSTER_DOMAIN}"
    - "kiali.${CLUSTER_DOMAIN}"
    - "jaeger.${CLUSTER_DOMAIN}"
    - "tracing.${CLUSTER_DOMAIN}"
    - "chat.${CLUSTER_DOMAIN}"
    - "agent.${CLUSTER_DOMAIN}"
    - "memory.${CLUSTER_DOMAIN}"
    - "alertmanager.${CLUSTER_DOMAIN}"
    - "prometheus.${CLUSTER_DOMAIN}"
    - "pushgateway.${CLUSTER_DOMAIN}"
    - "app.${CLUSTER_DOMAIN}"
    - "sso.${CLUSTER_DOMAIN}"
    - "api.${CLUSTER_DOMAIN}"
    - "www.${CLUSTER_DOMAIN}"
    - "${CLUSTER_DOMAIN}"
